apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "commerce-platform.fullname" . }}-config
  labels:
    {{- include "commerce-platform.labels" . | nindent 4 }}
data:
  environment: {{ .Values.global.environment | quote }}
  catalog-seed-data: {{ .Values.catalog.seedData | quote }}
  catalog-base-url: {{ printf "http://%s-catalog" (include "commerce-platform.fullname" .) | quote }}

